- name: Install repo software package for {{ ansible_distribution }}
  apt:
    name: "{{ repo_software_package }}"
    state: present
  environment: "{{ proxy_env }}"
  when:
    - use_proxy is defined
    - use_proxy

- name: Install repo software package for {{ ansible_distribution }}
  apt:
    name: "{{ repo_software_package }}"
    state: present
  when: (use_proxy is not defined) or (not use_proxy)

- name: Add MariaDB Repository Key for {{ ansible_distribution }}
  apt_key:
    url: "{{ key_url }}"
    state: present
  environment: "{{ proxy_env }}"
  when:
    - use_proxy is defined
    - use_proxy
    - stage == 'development'

- name: add mariadb key
  template:
    src: mariadb.key
    dest: /tmp/mariadb.key
    owner: root
    group: root
    mode: 0644

- name: add mariadb apt-key
  ansible.builtin.apt_key:
    file: /tmp/mariadb.key
    state: present

- name: Add MariaDB Repository for {{ ansible_distribution }}
  apt_repository:
    repo: "{{ repo_deb }} {{ ansible_distribution_release }}  main"
    state: present
    filename: mariadb
  environment: "{{ proxy_env }}"
  when:
    - use_proxy is defined
    - use_proxy
  register: addmariadbrepo

- name: Add MariaDB Repository for {{ ansible_distribution }}
  apt_repository:
    repo: "{{ repo_deb }} {{ ansible_distribution_release }}  main"
    state: present
    filename: mariadb
  when: (use_proxy is not defined) or (not use_proxy)
  register: addmariadbrepo

- name: Install Mariadb server for {{ ansible_distribution }}
  apt:
    name: "{{ mariadb_packages }}"
    state: present
  environment: "{{ proxy_env }}"
  when:
    - use_proxy is defined
    - use_proxy

- name: Install Mariadb server for {{ ansible_distribution }}
  apt:
    name: "{{ mariadb_packages }}"
    state: present
  when: (use_proxy is not defined) or (not use_proxy)
