#!/bin/bash
# ---------------------------------------------
# log圧縮ファイルの肥大化対策
# ---------------------------------------------
arcdir=/mnt/storage01/`hostname`/apache2/
echo ${arcdir}
# 10日経過した圧縮ファイルはアーカイブディレクトリに移動
find /var/log/apache2/*.gz -mtime +10 | xargs -I% mv % ${arcdir}

# 2年(365*2)経過した圧縮ファイルは標準細則の保持ルール対象外の為、アーカイブディレクトリから消去
find ${arcdir}/*.gz -mtime +730  -delete
