require 'rake'
require 'rspec/core/rake_task'

# cacti配列にテスト対象を定義
cacti=%w(01_linux_base 02_httpd 03_db 04_cacti 05_spine  06_edm  07_zabbix-agent  08_images 09_html)
provi=%w(linux-base)

# hostnameはserverspec実行端末の/etc/hostsで解決する方式で、開発環境／検証環境／商用環境の共有を図る。
hosts = [
  {
    :name  => 'cacti01',
    :roles => cacti,
  },
  {
    :name  => 'cacti02',
    :roles => cacti,
  },
  {
    :name  => 'cacti03',
    :roles => cacti,
  },
  {
    :name  => 'provisioning',
    :roles => provi,
  },
]

# テスト対象の変数展開
hosts = hosts.map do |host|
  {
    :name       => host[:name],
    :short_name => host[:name].split('.')[0],
    :roles      => host[:roles],
  }
end

# rake serverspecコマンドとして実行する[role形式テスト]の定義 
desc "Run serverspec to all hosts"
task :serverspec => 'serverspec:all'

namespace :serverspec do
  task :all => hosts.map { |h| 'serverspec:' + h[:short_name] }
  hosts.each do |host|
    desc "Run serverspec to #{host[:name]}"
    RSpec::Core::RakeTask.new(host[:short_name].to_sym) do |t|
      ENV['TARGET_HOST'] = host[:name]
      t.pattern = 'spec/{' + host[:roles].join(',') + '}/*_spec.rb'
    end
  end
end

