- name: Update and upgrade apt packages
  apt:
    upgrade: "yes"
    update_cache: yes

# rubyとunzipをインストール
- name: instration ruby stable version
  become: yes
  apt:
    name:
      - software-properties-common
      - ruby
      - ruby-dev
      - unzip

# 手動でppa:ansible/ansibleのGPGKEYを追加
# ref: https://launchpad.net/~ansible/+archive/ubuntu/ansible
- name: uplaod ppa:ansible Key file
  become: yes
  template:
    src:  tmp/ppa_ansible.key
    dest: /tmp/ppa_ansible.key
    owner: root
    group: root
    mode: 0644

- name: add ppa:ansible apt-key
  become: yes
  ansible.builtin.apt_key:
    file: /tmp/ppa_ansible.key
    state: present

# 手動で/etc/apt/sources.listにリポジトリを追加
- name: Add ppa:ansible/ansible Repository
  become: yes
  apt_repository:
    repo: "deb https://ppa.launchpadcontent.net/ansible/ansible/ubuntu {{os_alias}} main"
    state: present
    filename: ppa_ansible

# 手動でgoogle-chromeのGPGKEYを追加
# ref: https://qiita.com/ekzemplaro/items/11539f5bd9b80a6c7dca
# ref: https://www.slimjet.com/chrome/google-chrome-old-version.php 
- name: uplaod google-chrome Key file
  template:
    src:  tmp/google-chrome.key
    dest: /tmp/google-chrome.key
    owner: root
    group: root
    mode: 0644

- name: add google-chrome apt-key
  become: yes
  ansible.builtin.apt_key:
    file: /tmp/google-chrome.key
    state: present

# 手動で/etc/apt/sources.listにリポジトリを追加
- name: Add google-chrome Repository
  become: yes
  apt_repository:
    repo: "deb http://dl.google.com/linux/chrome/deb/ stable main"
    state: present
    filename: google-chrome


# Aptリポジトリを追加したのでパッケージ取得のためにaptリポジトリの更新
- name: Apt update
  become: yes
  apt:
    update_cache: yes

- name: Install google-chrome with specified version 
  become: yes
  apt:
    name: "google-chrome-stable"

- name: chrome-version check
  shell: "google-chrome --version | cut -d' ' -f3"
  register: chrome_version

- name: debug chrome_version
  debug:
    msg: "{{ chrome_version.stdout }}"

- name: download chromedriver-linux64.zip
  ansible.builtin.get_url:
    url: "https://storage.googleapis.com/chrome-for-testing-public/{{ chrome_version.stdout }}/linux64/chromedriver-linux64.zip"
    dest: /tmp/chromedriver-linux64.zip
    owner: develop
    group: develop
    mode: 0775

- name: unarchive_dir_check
  stat:
    path: "/tmp/chromedriver-linux64"
  register: tmpcd


#- name: unzip chromedriver-linux64.zip
#  become: yes
#  command:
#    cmd: "unzip /tmp/chromedriver-linux64.zip"
#  when:
#    - tmpcd.stat.exists == false

- name: unzip chromedriver-linux64.zip
  ansible.builtin.unarchive:
    src: "/tmp/chromedriver-linux64.zip"
    dest: /tmp/
    remote_src: yes
  when:
    - tmpcd.stat.exists == false


# google-chrome --version | cut -d' ' -f3`
# Chrome-driverのインストール
# ref: https://voicetechno-jp.secure-web.jp/ChromeDriverV115orNewer.html  
# download: https://developer.chrome.com/docs/chromedriver/downloads?hl=ja
